<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddExperienceLink</name>
   <tag></tag>
   <elementGuidId>c71ffe48-0720-45c9-b464-594f75310a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
